title: Jekyll for Github Projects
description: >
  Github プロジェクトページのドキュメント用に作成されたJekyllテーマです｡

baseurl: /jekyll-for-github-projects
url: https://ejointjp.github.io

author:
  name: e-JOINT.jp
  email:
  github: ejointjp
  twitter: ejointjp

project_repo: auto # https://github.com の後のリポジトリページのパス｡「'auto'」に設定すると､/{{ author.github }}/{{ site.baseurl }}となります｡
google_analytics_tracking_id:
front_page_overview: false
display_home_in_menu: false
default_sidebar: tocjs # default ''

highlighter: rouge

permalink: pretty

sass:
  style: compressed

gems:
  - jekyll-feed
  - jekyll-sitemap
