title: kamioteppei.github.io
description: >
  kamioteppeiの学習備忘録です｡

baseurl: /
url: https://kamioteppei.github.io

author:
  name: kamioteppei
  email:
  github: kamioteppei
  twitter:

project_repo: auto # https://github.com の後のリポジトリページのパス｡「'auto'」に設定すると､/{{ author.github }}/{{ site.baseurl }}となります｡
google_analytics_tracking_id:
front_page_overview: false
display_home_in_menu: true
default_sidebar: tocjs # default ''

highlighter: rouge
permalink: pretty

sass:
  style: compressed

exclude:
  - gulpfile.js
  - package.json

gems:
  - jekyll-feed
  - jekyll-sitemap

collections:
  memos:
    output: true
    permalink: /:collection/:name

markdown: kramdown
